export const SOLAR_CONSTANTS = {
  DEFAULT_PEAK_SUN_HOURS: 4,
  DEFAULT_PERFORMANCE_RATIO: 0.65,

  DEFAULT_POWER_FACTOR: 0.8,

  INVERTER_WORKING_MARGIN: 1.25,

  BATTERY_DOD_TUBULAR: 0.8,
  BATTERY_DOD_LITHIUM: 0.8,

  BATTERY_EFFICIENCY: 0.8,

  PV_SAFETY_FACTOR: 1.25,
  VOC_SAFETY_FACTOR: 1.15,

  MIN_ILR_RATIO: 1.2,
  MAX_ILR_RATIO: 1.3,

  PWM_MAX_POWER: 300,

  DEFAULT_MAX_VOLTAGE_DROP: 0.03,

  COPPER_RESISTIVITY: 0.0179,
} as const;